import type { Day } from "./types";

export const DAYS: Day[] = [
  {
    id: "tue",
    label: "Today",
    date: "Tue · 15 Apr",
    isToday: true,
    options: [
      {
        id: "t-veg",
        line: "Vegetarian",
        name: "Spinach & ricotta lasagna",
        color: "#C87865",
        pattern: 45,
        tags: ["vegetarian"],
        climate: 0.8,
        climateLabel: "low",
        desc: "Layered pasta with spinach, ricotta and tomato. Garden salad, bread.",
      },
      {
        id: "t-nord",
        line: "Nordic",
        name: "Cod with dill potatoes",
        color: "#8FA67A",
        pattern: 90,
        tags: ["fish", "gluten-free"],
        climate: 1.4,
        climateLabel: "medium",
        desc: "Oven-baked cod, browned butter, dill potatoes, lemon.",
      },
      {
        id: "t-str",
        line: "Street food",
        name: "Bulgogi bao buns",
        color: "#E4A866",
        pattern: 20,
        tags: ["meat"],
        climate: 2.1,
        climateLabel: "high",
        desc: "Steamed buns, Korean beef, pickled cucumber, sesame.",
      },
    ],
  },
  {
    id: "mon",
    label: "Yesterday",
    date: "Mon · 14 Apr",
    isToday: false,
    options: [
      {
        id: "m-veg",
        line: "Vegetarian",
        name: "Chickpea curry",
        color: "#D49A5C",
        pattern: 60,
        tags: ["vegan"],
        climate: 0.6,
        climateLabel: "low",
        desc: "Chickpea & spinach curry, basmati rice, naan.",
      },
      {
        id: "m-nord",
        line: "Nordic",
        name: "Meatballs & lingon",
        color: "#A6634A",
        pattern: 30,
        tags: ["meat"],
        climate: 2.4,
        climateLabel: "high",
        desc: "Classic Swedish meatballs, cream sauce, lingonberry, mash.",
      },
      {
        id: "m-str",
        line: "Street food",
        name: "Banh mi",
        color: "#9BB07C",
        pattern: 75,
        tags: ["meat"],
        climate: 1.6,
        climateLabel: "medium",
        desc: "Pork belly, pickled carrot, coriander, chili mayo baguette.",
      },
    ],
  },
];

export const QUICK_TAGS = {
  positive: ["filling", "fresh", "balanced"],
  negative: ["bland", "dry", "overcooked", "small portion"],
} as const;
