ALTER TABLE "Review" ADD COLUMN "tags" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];

ALTER TABLE "Lunch" ADD COLUMN "line" TEXT NOT NULL DEFAULT 'Vegetarian';
ALTER TABLE "Lunch" ADD COLUMN "description" TEXT NOT NULL DEFAULT '';

ALTER TABLE "Review" DROP CONSTRAINT IF EXISTS "Review_servingId_fkey";
ALTER TABLE "Review" ADD CONSTRAINT "Review_servingId_fkey" FOREIGN KEY ("servingId") REFERENCES "Serving"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Serving" DROP CONSTRAINT IF EXISTS "Serving_lunchId_fkey";
ALTER TABLE "Serving" ADD CONSTRAINT "Serving_lunchId_fkey" FOREIGN KEY ("lunchId") REFERENCES "Lunch"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Ingredient" DROP CONSTRAINT IF EXISTS "Ingredient_lunchId_fkey";
ALTER TABLE "Ingredient" ADD CONSTRAINT "Ingredient_lunchId_fkey" FOREIGN KEY ("lunchId") REFERENCES "Lunch"("id") ON DELETE CASCADE ON UPDATE CASCADE;
