// TODO: replace with API calls once Prisma models land.
import { Suggestion } from "@/services/suggestionService";
import { LINE_COLOR } from "./colors";
import type { Kpi, MealComment, MealStat, TrendSeries } from "./types";

export const MANAGER = {
  name: "Eva Magnusson",
  initials: "EM",
  firstName: "Eva",
  role: "Lunch manager",
  school: "Chalmers · kårrestaurangen",
};

export const WEEK_STAT = {
  week: "Week 17",
  ratingsThisWeek: 312,
};

export const SUGGESTIONS_BADGE = 12;

export const MEALS: MealStat[] = [
  {
    id: "bolognese",
    name: "Pasta bolognese",
    line: "Nordic",
    tags: ["meat", "pasta"],
    rating: 4.6,
    votes: 198,
    distribution: [3, 7, 18, 52, 118],
    co2: 2.2,
    climate: "low",
    lastServed: "2d ago",
    ingredients: [
      { name: "Pasta", amount: 120, unit: "g" },
      { name: "Beef mince", amount: 90, unit: "g" },
      { name: "Tomato sauce", amount: 80, unit: "ml" },
      { name: "Yellow onion", amount: 40, unit: "g" },
      { name: "Parmesan", amount: 10, unit: "g" },
    ],
  },
  {
    id: "tacos",
    name: "Tacos",
    line: "Street food",
    tags: ["meat", "mexican"],
    rating: 4.7,
    votes: 211,
    distribution: [2, 5, 14, 58, 132],
    co2: 2.1,
    climate: "low",
    lastServed: "1w ago",
    ingredients: [],
  },
  {
    id: "meatballs",
    name: "Meatballs & mash",
    line: "Nordic",
    tags: ["meat", "classic"],
    rating: 4.4,
    votes: 176,
    distribution: [4, 9, 22, 58, 83],
    co2: 2.4,
    climate: "low",
    lastServed: "3d ago",
    ingredients: [],
  },
  {
    id: "lasagna",
    name: "Vegetarian lasagna",
    line: "Vegetarian",
    tags: ["vegetarian", "pasta"],
    rating: 4.1,
    votes: 164,
    distribution: [6, 11, 29, 54, 64],
    co2: 0.8,
    climate: "low",
    lastServed: "5d ago",
    ingredients: [],
  },
  {
    id: "baobuns",
    name: "Bulgogi bao buns",
    line: "Street food",
    tags: ["meat", "asian"],
    rating: 4.3,
    votes: 151,
    distribution: [4, 9, 20, 46, 72],
    co2: 1.9,
    climate: "low",
    lastServed: "2w ago",
    ingredients: [],
  },
  {
    id: "curry",
    name: "Chickpea curry",
    line: "Vegetarian",
    tags: ["vegan", "rice", "curry"],
    rating: 4.0,
    votes: 142,
    distribution: [5, 10, 27, 52, 48],
    co2: 0.6,
    climate: "low",
    lastServed: "1w ago",
    ingredients: [
      { name: "Chickpeas", amount: 150, unit: "g" },
      { name: "Coconut milk", amount: 100, unit: "ml" },
      { name: "Basmati rice", amount: 90, unit: "g" },
      { name: "Curry paste", amount: 20, unit: "g" },
      { name: "Spinach", amount: 30, unit: "g" },
    ],
  },
  {
    id: "cod",
    name: "Cod with dill potatoes",
    line: "Nordic",
    tags: ["fish"],
    rating: 3.4,
    votes: 188,
    distribution: [14, 22, 68, 51, 33],
    co2: 1.4,
    climate: "med",
    lastServed: "3w ago",
    ingredients: [],
  },
  {
    id: "halloumi",
    name: "Halloumi bowl",
    line: "Street food",
    tags: ["vegetarian", "bowl"],
    rating: 3.9,
    votes: 97,
    distribution: [4, 8, 24, 36, 25],
    co2: 1.8,
    climate: "med",
    lastServed: "2w ago",
    ingredients: [
      { name: "Halloumi", amount: 80, unit: "g" },
      { name: "Quinoa", amount: 90, unit: "g" },
      { name: "Roast vegetables", amount: 120, unit: "g" },
      { name: "Tahini dressing", amount: 30, unit: "ml" },
    ],
  },
  {
    id: "curry-chick",
    name: "Chicken tikka",
    line: "Street food",
    tags: ["meat", "rice", "curry"],
    rating: 4.2,
    votes: 134,
    distribution: [4, 7, 20, 48, 55],
    co2: 2.0,
    climate: "low",
    lastServed: "6d ago",
    ingredients: [],
  },
  {
    id: "soup",
    name: "Cauliflower soup",
    line: "Vegetarian",
    tags: ["vegan", "soup"],
    rating: 1.9,
    votes: 102,
    distribution: [46, 28, 18, 7, 3],
    co2: 0.5,
    climate: "low",
    lastServed: "8w ago",
    ingredients: [],
  },
  {
    id: "stew",
    name: "Fish stew",
    line: "Nordic",
    tags: ["fish"],
    rating: 2.3,
    votes: 138,
    distribution: [48, 36, 28, 18, 8],
    co2: 1.4,
    climate: "med",
    lastServed: "7w ago",
    ingredients: [],
  },
  {
    id: "quiche",
    name: "Spinach quiche",
    line: "Vegetarian",
    tags: ["vegetarian"],
    rating: 3.1,
    votes: 84,
    distribution: [11, 15, 28, 20, 10],
    co2: 1.1,
    climate: "med",
    lastServed: "3w ago",
    ingredients: [],
  },
  {
    id: "ramen",
    name: "Miso ramen",
    line: "Street food",
    tags: ["vegetarian", "asian"],
    rating: 4.5,
    votes: 128,
    distribution: [3, 5, 14, 40, 66],
    co2: 1.2,
    climate: "low",
    lastServed: "5d ago",
    ingredients: [],
  },
  {
    id: "paella",
    name: "Seafood paella",
    line: "Street food",
    tags: ["fish", "rice"],
    rating: 4.0,
    votes: 88,
    distribution: [4, 8, 22, 32, 22],
    co2: 1.8,
    climate: "med",
    lastServed: "12d ago",
    ingredients: [],
  },
  {
    id: "pancakes",
    name: "Swedish pancakes w/ jam",
    line: "Nordic",
    tags: ["vegetarian", "classic"],
    rating: 4.6,
    votes: 189,
    distribution: [3, 6, 15, 48, 117],
    co2: 0.9,
    climate: "low",
    lastServed: "8d ago",
    ingredients: [],
  },
  {
    id: "stroga",
    name: "Mushroom stroganoff",
    line: "Vegetarian",
    tags: ["vegetarian", "classic"],
    rating: 3.7,
    votes: 94,
    distribution: [5, 12, 26, 34, 17],
    co2: 0.7,
    climate: "med",
    lastServed: "3w ago",
    ingredients: [],
  },
  {
    id: "pho",
    name: "Pho (chicken)",
    line: "Street food",
    tags: ["meat", "soup", "asian"],
    rating: 4.3,
    votes: 76,
    distribution: [2, 5, 12, 27, 30],
    co2: 1.6,
    climate: "low",
    lastServed: "2w ago",
    ingredients: [],
  },
  {
    id: "shak",
    name: "Shakshuka",
    line: "Street food",
    tags: ["vegetarian", "new"],
    rating: null,
    votes: 0,
    distribution: [0, 0, 0, 0, 0],
    co2: 0.9,
    climate: null,
    lastServed: "never",
    ingredients: [],
  },
  {
    id: "bowl",
    name: "Roast squash bowl",
    line: "Vegetarian",
    tags: ["vegan", "bowl", "new"],
    rating: null,
    votes: 0,
    distribution: [0, 0, 0, 0, 0],
    co2: 0.5,
    climate: null,
    lastServed: "never",
    ingredients: [],
  },
  {
    id: "pork",
    name: "Pork schnitzel",
    line: "Nordic",
    tags: ["meat", "classic"],
    rating: 3.2,
    votes: 112,
    distribution: [18, 22, 34, 26, 12],
    co2: 2.8,
    climate: "med",
    lastServed: "6w ago",
    ingredients: [],
  },
  {
    id: "salmon",
    name: "Glazed salmon",
    line: "Nordic",
    tags: ["fish"],
    rating: 4.2,
    votes: 143,
    distribution: [4, 8, 22, 48, 61],
    co2: 1.5,
    climate: "low",
    lastServed: "1w ago",
    ingredients: [],
  },
  {
    id: "pea",
    name: "Yellow pea soup",
    line: "Nordic",
    tags: ["vegan", "soup"],
    rating: 2.8,
    votes: 78,
    distribution: [22, 18, 20, 12, 6],
    co2: 0.4,
    climate: "low",
    lastServed: "9w ago",
    ingredients: [],
  },
  {
    id: "dahl",
    name: "Red lentil dahl",
    line: "Vegetarian",
    tags: ["vegan", "curry"],
    rating: 4.1,
    votes: 118,
    distribution: [4, 8, 20, 40, 46],
    co2: 0.5,
    climate: "low",
    lastServed: "4d ago",
    ingredients: [],
  },
  {
    id: "risotto",
    name: "Mushroom risotto",
    line: "Vegetarian",
    tags: ["vegetarian", "rice"],
    rating: 3.9,
    votes: 102,
    distribution: [5, 10, 24, 38, 25],
    co2: 0.9,
    climate: "med",
    lastServed: "2w ago",
    ingredients: [],
  },
];

export const COMMENTS: MealComment[] = [
  {
    id: 1,
    mealId: "stew",
    mealName: "Fish stew",
    rating: 1,
    text: "Too fishy, and the sauce was watery. Half the class binned it.",
    when: "2h ago",
    tags: ["cold", "weird texture"],
  },
  {
    id: 2,
    mealId: "tacos",
    mealName: "Tacos",
    rating: 5,
    text: "Please do this every week. Seriously.",
    when: "4h ago",
    tags: ["more please", "loved it"],
  },
  {
    id: 3,
    mealId: "soup",
    mealName: "Cauliflower soup",
    rating: 2,
    text: "The bread was nice but the soup was bland.",
    when: "Yesterday",
    tags: ["bland"],
  },
  {
    id: 4,
    mealId: "bolognese",
    mealName: "Pasta bolognese",
    rating: 5,
    text: "Best version this term — way more meat.",
    when: "Yesterday",
    tags: ["perfect"],
  },
  {
    id: 5,
    mealId: "stew",
    mealName: "Fish stew",
    rating: 2,
    text: "I don't like fish but this was worse than usual.",
    when: "Yesterday",
    tags: ["weird texture"],
  },
  {
    id: 6,
    mealId: "baobuns",
    mealName: "Bulgogi bao buns",
    rating: 5,
    text: "Genuinely amazing, please keep the street-food line.",
    when: "2d ago",
    tags: ["loved it"],
  },
  {
    id: 7,
    mealId: "lasagna",
    mealName: "Vegetarian lasagna",
    rating: 4,
    text: "Good but the portion was a bit small.",
    when: "2d ago",
    tags: ["too small"],
  },
  {
    id: 8,
    mealId: "soup",
    mealName: "Cauliflower soup",
    rating: 1,
    text: "I had to throw half away.",
    when: "3d ago",
    tags: ["cold"],
  },
  {
    id: 9,
    mealId: "curry",
    mealName: "Chickpea curry",
    rating: 4,
    text: "Rice was a bit dry but sauce was great.",
    when: "3d ago",
    tags: ["dry"],
  },
  {
    id: 10,
    mealId: "cod",
    mealName: "Cod with dill potatoes",
    rating: 3,
    text: "Fine.",
    when: "4d ago",
    tags: [],
  },
  {
    id: 11,
    mealId: "meatballs",
    mealName: "Meatballs & mash",
    rating: 5,
    text: "Classic. Don't change anything.",
    when: "4d ago",
    tags: ["perfect"],
  },
  {
    id: 12,
    mealId: "halloumi",
    mealName: "Halloumi bowl",
    rating: 4,
    text: "The dressing made it.",
    when: "5d ago",
    tags: ["loved it"],
  },
  {
    id: 13,
    mealId: "stew",
    mealName: "Fish stew",
    rating: 1,
    text: "Cold by the time I got to the front of the queue.",
    when: "5d ago",
    tags: ["cold"],
  },
  {
    id: 14,
    mealId: "soup",
    mealName: "Cauliflower soup",
    rating: 3,
    text: "Better with more salt and pepper out on the tables.",
    when: "6d ago",
    tags: ["bland"],
  },
  {
    id: 15,
    mealId: "bolognese",
    mealName: "Pasta bolognese",
    rating: 5,
    text: "Hits the spot every time.",
    when: "1w ago",
    tags: ["perfect", "more please"],
  },
  {
    id: 16,
    mealId: "salmon",
    mealName: "Glazed salmon",
    rating: 4,
    text: "Glaze was on point but a bit dry inside.",
    when: "1w ago",
    tags: ["dry"],
  },
];

export const KPIS: Kpi[] = [
  {
    label: "Avg rating · week",
    value: "4.1",
    trend: "↑ 0.3",
    sub: "vs. last week",
    spark: [3.7, 3.9, 3.8, 4.0, 3.9, 4.1, 4.1],
    color: "var(--color-tea)",
  },
  {
    label: "Ratings today",
    value: "184",
    trend: "↑ 22%",
    sub: "45% of today's diners",
    spark: [80, 110, 95, 130, 150, 170, 184],
    color: "var(--color-amber)",
  },
  {
    label: "Comments / week",
    value: "34",
    trend: "↑ 15%",
    sub: "12% of ratings",
    spark: [20, 24, 22, 28, 30, 34, 34],
    color: "var(--color-rose)",
  },
];

export const TREND_X_LABELS = [
  "W15 Mon",
  "Tue",
  "Wed",
  "Thu",
  "Fri",
  "W16 Mon",
  "Tue",
  "Wed",
  "Thu",
  "Fri",
  "W17 Mon",
  "Tue",
];

export const TREND_SERIES: TrendSeries[] = [
  {
    name: "Nordic",
    color: LINE_COLOR.Nordic,
    data: [3.2, 4.1, 3.9, 3.0, 2.3, 3.8, 4.2, 3.5, 4.6, 4.2, 2.8, 4.4],
  },
  {
    name: "Vegetarian",
    color: LINE_COLOR.Vegetarian,
    data: [3.8, 2.1, 4.0, 3.9, 3.7, 3.6, 3.2, 4.0, 3.9, 4.1, 1.9, 4.1],
  },
  {
    name: "Street food",
    color: LINE_COLOR["Street food"],
    data: [4.3, 4.5, 4.2, 4.4, 4.7, 4.2, 4.4, 4.3, 4.6, 4.7, 4.3, 4.3],
  },
];

export const TREND_FOOTNOTES = [
  {
    label: "Best day",
    value: "Thu W16",
    sub: "4.6 avg · tacos + bao",
    tone: "var(--color-sage)",
  },
  {
    label: "Worst day",
    value: "Mon W17",
    sub: "2.8 avg · soup binned",
    tone: "var(--color-rose)",
  },
  {
    label: "3-week delta",
    value: "+0.4",
    sub: "vs. W15 average",
    tone: "var(--color-tea)",
  },
];

export const MEAL_TREND_X_LABELS = [
  "Jan",
  "Jan",
  "Feb",
  "Feb",
  "Feb",
  "Mar",
  "Mar",
  "Apr",
  "Apr",
];

export const MEAL_TREND_SAMPLE = [3.9, 4.1, 4.0, 4.3, 4.2, 4.2, 4.4, 4.5, 4.6];

export const MEAL_TAG_BARS = [
  { label: "perfect", count: 52, color: "var(--color-sage)" },
  { label: "more please", count: 41, color: "var(--color-sage)" },
  { label: "loved it", count: 38, color: "var(--color-sage)" },
  { label: "too small", count: 12, color: "var(--color-amber)" },
  { label: "too salty", count: 6, color: "var(--color-amber)" },
  { label: "cold", count: 3, color: "var(--color-rose)" },
];

export const SUGGESTIONS: Suggestion[] = [
  {
    id: 1,
    title: "Tacos",
    description: "I want more tacos because they are yummy!",
    postedDate: new Date("2026-05-11T13:27"),
    userDisplayName: "Frida",
  },
  {
    id: 2,
    title: "I'm confused",
    description:
      "Why are so many people complaining about the school food, it's delicious",
    postedDate: new Date("2026-05-11T13:24"),
    userDisplayName: "Alice",
  },
  {
    id: 3,
    title: "I want more sweet foods",
    description:
      "I loveeee sugary sweets and pancakes. We should have more of that",
    postedDate: new Date(),
    userDisplayName: "",
  },
];

export function getMealById(id: string): MealStat | undefined {
  return MEALS.find(m => m.id === id);
}

export function getCommentsForMeal(mealId: string): MealComment[] {
  return COMMENTS.filter(c => c.mealId === mealId);
}
