// In-memory seed backing the create/edit meal flow until that path is
// wired to the database. Read-only views read from the statistics service.
import type { MealStat } from "./types";

export const MEALS: MealStat[] = [
  {
    id: "bolognese",
    name: "Pasta bolognese",
    line: "Nordic",
    tags: ["meat", "pasta"],
    rating: 4.6,
    votes: 198,
    distribution: [3, 7, 18, 52, 118],
    co2: 2.2,
    climate: "low",
    lastServed: "2d ago",
    ingredients: [
      { name: "Pasta", amount: 120, unit: "g" },
      { name: "Beef mince", amount: 90, unit: "g" },
      { name: "Tomato sauce", amount: 80, unit: "ml" },
      { name: "Yellow onion", amount: 40, unit: "g" },
      { name: "Parmesan", amount: 10, unit: "g" },
    ],
  },
  {
    id: "tacos",
    name: "Tacos",
    line: "Street food",
    tags: ["meat", "mexican"],
    rating: 4.7,
    votes: 211,
    distribution: [2, 5, 14, 58, 132],
    co2: 2.1,
    climate: "low",
    lastServed: "1w ago",
    ingredients: [],
  },
  {
    id: "meatballs",
    name: "Meatballs & mash",
    line: "Nordic",
    tags: ["meat", "classic"],
    rating: 4.4,
    votes: 176,
    distribution: [4, 9, 22, 58, 83],
    co2: 2.4,
    climate: "low",
    lastServed: "3d ago",
    ingredients: [],
  },
  {
    id: "lasagna",
    name: "Vegetarian lasagna",
    line: "Vegetarian",
    tags: ["vegetarian", "pasta"],
    rating: 4.1,
    votes: 164,
    distribution: [6, 11, 29, 54, 64],
    co2: 0.8,
    climate: "low",
    lastServed: "5d ago",
    ingredients: [],
  },
  {
    id: "baobuns",
    name: "Bulgogi bao buns",
    line: "Street food",
    tags: ["meat", "asian"],
    rating: 4.3,
    votes: 151,
    distribution: [4, 9, 20, 46, 72],
    co2: 1.9,
    climate: "low",
    lastServed: "2w ago",
    ingredients: [],
  },
  {
    id: "curry",
    name: "Chickpea curry",
    line: "Vegetarian",
    tags: ["vegan", "rice", "curry"],
    rating: 4.0,
    votes: 142,
    distribution: [5, 10, 27, 52, 48],
    co2: 0.6,
    climate: "low",
    lastServed: "1w ago",
    ingredients: [
      { name: "Chickpeas", amount: 150, unit: "g" },
      { name: "Coconut milk", amount: 100, unit: "ml" },
      { name: "Basmati rice", amount: 90, unit: "g" },
      { name: "Curry paste", amount: 20, unit: "g" },
      { name: "Spinach", amount: 30, unit: "g" },
    ],
  },
  {
    id: "cod",
    name: "Cod with dill potatoes",
    line: "Nordic",
    tags: ["fish"],
    rating: 3.4,
    votes: 188,
    distribution: [14, 22, 68, 51, 33],
    co2: 1.4,
    climate: "med",
    lastServed: "3w ago",
    ingredients: [],
  },
  {
    id: "halloumi",
    name: "Halloumi bowl",
    line: "Street food",
    tags: ["vegetarian", "bowl"],
    rating: 3.9,
    votes: 97,
    distribution: [4, 8, 24, 36, 25],
    co2: 1.8,
    climate: "med",
    lastServed: "2w ago",
    ingredients: [
      { name: "Halloumi", amount: 80, unit: "g" },
      { name: "Quinoa", amount: 90, unit: "g" },
      { name: "Roast vegetables", amount: 120, unit: "g" },
      { name: "Tahini dressing", amount: 30, unit: "ml" },
    ],
  },
  {
    id: "curry-chick",
    name: "Chicken tikka",
    line: "Street food",
    tags: ["meat", "rice", "curry"],
    rating: 4.2,
    votes: 134,
    distribution: [4, 7, 20, 48, 55],
    co2: 2.0,
    climate: "low",
    lastServed: "6d ago",
    ingredients: [],
  },
  {
    id: "soup",
    name: "Cauliflower soup",
    line: "Vegetarian",
    tags: ["vegan", "soup"],
    rating: 1.9,
    votes: 102,
    distribution: [46, 28, 18, 7, 3],
    co2: 0.5,
    climate: "low",
    lastServed: "8w ago",
    ingredients: [],
  },
  {
    id: "stew",
    name: "Fish stew",
    line: "Nordic",
    tags: ["fish"],
    rating: 2.3,
    votes: 138,
    distribution: [48, 36, 28, 18, 8],
    co2: 1.4,
    climate: "med",
    lastServed: "7w ago",
    ingredients: [],
  },
  {
    id: "quiche",
    name: "Spinach quiche",
    line: "Vegetarian",
    tags: ["vegetarian"],
    rating: 3.1,
    votes: 84,
    distribution: [11, 15, 28, 20, 10],
    co2: 1.1,
    climate: "med",
    lastServed: "3w ago",
    ingredients: [],
  },
  {
    id: "ramen",
    name: "Miso ramen",
    line: "Street food",
    tags: ["vegetarian", "asian"],
    rating: 4.5,
    votes: 128,
    distribution: [3, 5, 14, 40, 66],
    co2: 1.2,
    climate: "low",
    lastServed: "5d ago",
    ingredients: [],
  },
  {
    id: "paella",
    name: "Seafood paella",
    line: "Street food",
    tags: ["fish", "rice"],
    rating: 4.0,
    votes: 88,
    distribution: [4, 8, 22, 32, 22],
    co2: 1.8,
    climate: "med",
    lastServed: "12d ago",
    ingredients: [],
  },
  {
    id: "pancakes",
    name: "Swedish pancakes w/ jam",
    line: "Nordic",
    tags: ["vegetarian", "classic"],
    rating: 4.6,
    votes: 189,
    distribution: [3, 6, 15, 48, 117],
    co2: 0.9,
    climate: "low",
    lastServed: "8d ago",
    ingredients: [],
  },
  {
    id: "stroga",
    name: "Mushroom stroganoff",
    line: "Vegetarian",
    tags: ["vegetarian", "classic"],
    rating: 3.7,
    votes: 94,
    distribution: [5, 12, 26, 34, 17],
    co2: 0.7,
    climate: "med",
    lastServed: "3w ago",
    ingredients: [],
  },
  {
    id: "pho",
    name: "Pho (chicken)",
    line: "Street food",
    tags: ["meat", "soup", "asian"],
    rating: 4.3,
    votes: 76,
    distribution: [2, 5, 12, 27, 30],
    co2: 1.6,
    climate: "low",
    lastServed: "2w ago",
    ingredients: [],
  },
  {
    id: "shak",
    name: "Shakshuka",
    line: "Street food",
    tags: ["vegetarian", "new"],
    rating: null,
    votes: 0,
    distribution: [0, 0, 0, 0, 0],
    co2: 0.9,
    climate: null,
    lastServed: "never",
    ingredients: [],
  },
  {
    id: "bowl",
    name: "Roast squash bowl",
    line: "Vegetarian",
    tags: ["vegan", "bowl", "new"],
    rating: null,
    votes: 0,
    distribution: [0, 0, 0, 0, 0],
    co2: 0.5,
    climate: null,
    lastServed: "never",
    ingredients: [],
  },
  {
    id: "pork",
    name: "Pork schnitzel",
    line: "Nordic",
    tags: ["meat", "classic"],
    rating: 3.2,
    votes: 112,
    distribution: [18, 22, 34, 26, 12],
    co2: 2.8,
    climate: "med",
    lastServed: "6w ago",
    ingredients: [],
  },
  {
    id: "salmon",
    name: "Glazed salmon",
    line: "Nordic",
    tags: ["fish"],
    rating: 4.2,
    votes: 143,
    distribution: [4, 8, 22, 48, 61],
    co2: 1.5,
    climate: "low",
    lastServed: "1w ago",
    ingredients: [],
  },
  {
    id: "pea",
    name: "Yellow pea soup",
    line: "Nordic",
    tags: ["vegan", "soup"],
    rating: 2.8,
    votes: 78,
    distribution: [22, 18, 20, 12, 6],
    co2: 0.4,
    climate: "low",
    lastServed: "9w ago",
    ingredients: [],
  },
  {
    id: "dahl",
    name: "Red lentil dahl",
    line: "Vegetarian",
    tags: ["vegan", "curry"],
    rating: 4.1,
    votes: 118,
    distribution: [4, 8, 20, 40, 46],
    co2: 0.5,
    climate: "low",
    lastServed: "4d ago",
    ingredients: [],
  },
  {
    id: "risotto",
    name: "Mushroom risotto",
    line: "Vegetarian",
    tags: ["vegetarian", "rice"],
    rating: 3.9,
    votes: 102,
    distribution: [5, 10, 24, 38, 25],
    co2: 0.9,
    climate: "med",
    lastServed: "2w ago",
    ingredients: [],
  },
];

export function getMealById(id: string): MealStat | undefined {
  return MEALS.find(m => m.id === id);
}
